Console Error
FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/oroedu-4a86c/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9vcm9lZHUtNGE4NmMvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL2Jvb2tpbmdzL2luZGV4ZXMvXxABGhIKDmFwcHJvdmFsU3RhdHVzEAEaEwoPYm9va2luZ0NhdGVnb3J5EAEaCQoFcGhvbmUQARoNCglzdGFydERhdGUQARoMCghfX25hbWVfXxAB